"""empty message

Revision ID: 983cc4ded27a
Revises: 
Create Date: 2017-08-19 15:57:46.016439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983cc4ded27a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('memeber_since', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'memeber_since')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
